### ISSUE TITLE
Trying to install using msys2 on win 10, got an error.

### ISSUE THREAD

**Issue by victorbstan** [joshuaskelly/quake-cli-tools#16]
```
$ pip install quake-cli-tools
Collecting quake-cli-tools
  Downloading quake-cli-tools-1.2.1.tar.gz (14 kB)
Collecting Pillow>=6.2.0
  Downloading Pillow-7.1.2.tar.gz (38.9 MB)
     |████████████████████████████████| 38.9 MB 8.1 MB/s
Collecting progress>=1.5
  Downloading progress-1.5.tar.gz (5.8 kB)
Collecting vgio>=1.1.2
  Downloading vgio-1.1.2.tar.gz (71 kB)
     |████████████████████████████████| 71 kB 3.8 MB/s
Collecting svgwrite>=1.3.1
  Downloading svgwrite-1.4-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 3.0 MB/s
Collecting tabulate>=0.8.3
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting watchdog>=0.9.0
  Downloading watchdog-0.10.2.tar.gz (95 kB)
     |████████████████████████████████| 95 kB 2.8 MB/s
Collecting pathtools>=0.1.1
  Downloading pathtools-0.1.2.tar.gz (11 kB)
Using legacy setup.py install for quake-cli-tools, since package 'wheel' is not installed.
Using legacy setup.py install for Pillow, since package 'wheel' is not installed.
Using legacy setup.py install for progress, since package 'wheel' is not installed.
Using legacy setup.py install for vgio, since package 'wheel' is not installed.
Using legacy setup.py install for watchdog, since package 'wheel' is not installed.
Using legacy setup.py install for pathtools, since package 'wheel' is not installed.
Installing collected packages: Pillow, progress, vgio, svgwrite, tabulate, pathtools, watchdog, quake-cli-tools
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.exe -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fgmnhfy9/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fgmnhfy9/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v48y6w40/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/Pillow
         cwd: /tmp/pip-install-fgmnhfy9/Pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.msys-3.1.4-x86_64-3.8
    creating build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ContainerIO.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ExifTags.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/features.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/FontFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GdImageFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/Image.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageChops.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageCms.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageColor.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageDraw.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageFilter.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageFont.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageGrab.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageMath.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageMode.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageMorph.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageOps.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImagePalette.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImagePath.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageQt.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageSequence.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageShow.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageStat.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageTk.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageTransform.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImageWin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/JpegPresets.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PaletteFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PdfParser.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PSDraw.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/PyAccess.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/TarIO.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/TiffTags.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/WalImageFile.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/_binary.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/_util.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/_version.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/__init__.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    copying src/PIL/__main__.py -> build/lib.msys-3.1.4-x86_64-3.8/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.ci'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "/tmp/pip-install-fgmnhfy9/Pillow/setup.py", line 860, in <module>
        setup(
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-fgmnhfy9/Pillow/setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fgmnhfy9/Pillow/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.exe -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fgmnhfy9/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fgmnhfy9/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v48y6w40/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/Pillow Check the logs for full command output.

```

**Comment by joshuaskelly** [comment]
It looks like you are missing zlib and the `Pillow` dependecy is failing. Which is strange, because it should just be using a wheel for `Pillow`and not installing from source.

Can you try:
1. `pip install wheel`
2. `pip install quake-cli-tools`

Which Python distro are you using?

**Comment by victorbstan** [comment]
I'm using the one coming from `pacman -S python` on Msys2

**Comment by victorbstan** [comment]
Reported the issue on Pillows repo as well.

**Comment by victorbstan** [comment]
i got this to run, according to the instruction in the other issue post: `pacman -S mingw-w64-x86_64-python3-pillow`, but the quake-cli tools still don't seem to want to install.

**Comment by victorbstan** [comment]
Is there a different or better way to run these tools on Windows? I thought Msys2 was the recommended way.

**Comment by joshuaskelly** [comment]
I just use the official installers. I use MSYS for a GNU CLI environment.

See if you can get Pillow installed correctly and then you _should_ be able to install `quake-cli-tools`.

**Comment by victorbstan** [comment]
Ok, I just used the python installer and then PowerShell to do some pip updates and install the quake-cli, which worked :)
